version: "3.9"
services:
  webapp:
    image: thomaspilz/imdb-analyser
    env:
    - PORT: 5000
  db:
    image: postgres:14.0-alpine
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    networks:
      - web-net
    volumes:
      # mount postgres config
      - "./PostgreSQL/postgresql.conf:/etc/postgresql/postgresql.conf"
      # mount initialization script
      - "./PostgreSQL/sql-scripts:/docker-entrypoint-initdb.d"
      # create/ mount data volume to persist data even when containers are not running
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    environment:
      POSTGRES_PASSWORD: simplepw
      POSTGRES_USER: admin
      POSTGRES_DB: kpis

  pgadmin:
    image: dpage/pgadmin4:6.1
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
    networks:
      - mqtt-net
    volumes:
    # load server configuration
      - "./pgAdmin/servers.json:/pgadmin4/servers.json"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider" ,"localhost:80"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: simplepw